# Generated by Django 3.0.5 on 2020-04-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200415_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelanggan',
        ),
        migrations.AddField(
            model_name='customer',
            name='alamat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='umur',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
