# Generated by Django 3.0.5 on 2020-04-15 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200415_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='order',
            name='Kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sepeda Anak', 'Sepeda Anak'), ('Sepeda Gunung', 'Sepeda Gunung'), ('Sepeda Angin', 'Sepeda Angin')], max_length=200, null=True),
        ),
        
    ]
