# Generated by Django 3.0.5 on 2020-04-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200415_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pinjaman',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stok',
        ),
    ]
