# Generated by Django 3.0.5 on 2020-04-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200415_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pinjam',
            field=models.CharField(choices=[('1 Hari', '1 Hari'), ('1 Minggu', '1 Minggu'), ('1 Bulan', '1 Bulan')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Pinjam', 'Pinjam'), ('Selesai', 'Selesai')], max_length=200, null=True),
        ),
    ]
