# Generated by Django 3.0.5 on 2020-04-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200415_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stok',
        ),
    ]
