# Generated by Django 3.0.5 on 2020-04-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_product_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.FloatField(null=True),
        ),
    ]
