# Generated by Django 3.0.5 on 2020-04-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_product_product_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricemonth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='priceweek',
            field=models.FloatField(null=True),
        ),
    ]
